### ISSUE TITLE
onChangeItem is not called when select an item 

### ISSUE THREAD

**Issue by sailywebvillee** [hossein-zare/react-native-dropdown-picker#4]
Hello @hossein-zare 

Please help me as I am using this library for dropdown but onChangeItem is not getting called & I have also checked the example still no success. So can you please help us to identify the problem 

Thanks

**Comment by hossein-zare** [comment]
Hello @sailywebvillee 

Please show me how you are using the component, I need to see some code.
Android or iOS? and React Native version.

**Comment by hossein-zare** [comment]
Hello,

Thank you for reporting this issue, I fixed the bug.
Update the package to **2.1.0**

**Comment by ramagiox** [comment]
same here. 
still not working with version 2.1.1

**Comment by hossein-zare** [comment]
There's no problem with v2.1.1: [https://snack.expo.io/a6rDxpeU_](https://snack.expo.io/a6rDxpeU_)

Make sure you've installed the latest version from the `package.json`
Uninstall & Install it again.

If the issue persists, Please let me know.

**Comment by b-allard** [comment]
Hello,
 
I have the issue on Android. 
I have upgraded the package 2.1.3 to 3.0.4 and I stil have the issue.
I have tried with the example on snack.expo.io, no change, I still have the issue :'(

Please help me.

Thanks in Advance,
