### ISSUE TITLE
When Dropdown opens, dropdown container not taking z index, its not on the top of the below view

### ISSUE THREAD

**Issue by sagarkbluebenz** [hossein-zare/react-native-dropdown-picker#562]
Dropdown container forcing below content go down when opens dropdown. not able to apply z index

**Comment by pedrogs97** [comment]
Try this:
```
<View style={{ zIndex: 100 }}>
   <DropDownPicker {...} />
</View>
```

**Comment by carlossalasamper** [comment]
I have the same issue here 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/15049114/175829360-47dc2fb3-c625-431b-ab39-9337536636ef.png">

**Comment by lucasuracosta** [comment]
Same for me. It happens only when the dropdown opens to the bottom

**Comment by lucasuracosta** [comment]
> Try this:
> 
> ```
> <View style={{ zIndex: 100 }}>
>    <DropDownPicker {...} />
> </View>
> ```

¡This worked for me!

**Comment by kongshu612** [comment]
Hi there,
```<View style={_containerStyle} {...containerProps}>
            <TouchableOpacity style={_style} onPress={__onPress} onLayout={__onLayout} {...props} ref={onRef} pointerEvents={pointerEvents} disabled={disabled} testID={testID}>
                {_BodyComponent}
                {_ArrowComponent}
            </TouchableOpacity>
            {DropDownBodyComponent}
        </View>
```
Is it reasonable that we only apply the ZIndex to the **DropDownBodyComponent**?

**Comment by challme28** [comment]
> <View style={{ zIndex: 100 }}>
>    <DropDownPicker {...} />
> </View>

This hasn't work for me either

**Comment by devioand-aj** [comment]
I fixed this problem from https://github.com/hossein-zare/react-native-dropdown-picker/issues/450#issuecomment-976497649

**Comment by challme28** [comment]
Understanding the following helped me achieve the desired out in React Native
The way React Native zIndex hierarchy works is as follows:
```
<ComponentA>
  <Children1 zIndex={99}/>
  <Children2/>
<ComponentA/>
<ComponentB>
  <Children3/>
  <Children4 zIndex={9}/>
<ComponentB/>
```
`Children1` will always render below `Children3` and `Children4`. `Children4` is able to render on top of `Children3`. Should `Children3` have a Child with a zIndex equal to 999, it would still render below `Children4`.

**Comment by durgesh94** [comment]
> Try this:
> 
> ```
> <View style={{ zIndex: 100 }}>
>    <DropDownPicker {...} />
> </View>
> ```

If trying this,
on android devices the list is not scrolling, working fine on iOS devices.

**Comment by Linh-Vo** [comment]
still didn't work on IOS

**Comment by sharived** [comment]
I'm still having this issue.  If the dropDownDirection is Bottom then no matter where I set my zIndex it's always behind my other inputs.  If I set it to Top it works fine.  Very frustrating....

**Comment by hoon25** [comment]
If you're using the Dropdown component inside a FlatList, it seems that the height(z-index) is set according to the rendering order of the FlatList, and it cannot be changed using z-index. Although it's not a perfect solution, I resolved the issue by reversing the order of the FlatList's data and applying the {flexDirection: 'column-reverse'} property!
