### ISSUE TITLE
activeItemStyle doesn't work on multiple={true}

### ISSUE THREAD

**Issue by shaimeron** [hossein-zare/react-native-dropdown-picker#70]
In Index.js there's a line that checks if this.state.choice.value === item.value but this line only works for multiple={false} because when using multiple choices, this.state.choice is an array so this.state.choice.value returns undefined.
I'd be glad if you can fix this problem.
Thank You!

**Comment by hossein-zare** [comment]
Hello, 
Thank you for reporting the bug.

I'll fix it in the next version.

**Comment by mleister97** [comment]
When will you release the next version including this bugix? 
The beta is currently not working at all for me

**Comment by mleister97** [comment]
Also your bugfix commit does not work for me, I applied the changes of your commit... Have you tested it?

**Comment by hossein-zare** [comment]
@mleister97 Where did you install it? on Snack?
Please tell me more about it, warnings, errors, ...
Some of the requested features require a lot of time to be implemented.
I'll try to release a version today with the latest implemented features and bugfixes.

### Update
I published another Beta version with some bugfixes.

**Comment by LWlook** [comment]
I added 
`...((multiple && this.isSelected(item)) && this.props.activeLabelStyle)`
to the text-Tag on line 331 to your latest beta version. Now its working for me.

(with version 3.1.12-beta.1 alone, i wasn't able to color the text)

**Comment by mleister97** [comment]
@hossein-zare your changes are still not working for me.
I am using a multiple dropdown and want to color the text.

**Comment by mleister97** [comment]
> I added
> `...((multiple && this.isSelected(item)) && this.props.activeLabelStyle)`
> to the text-Tag on line 331 to your latest beta version. Now its working for me.
> 
> (with version 3.1.12-beta.1 alone, i wasn't able to color the text)

Seems fine for me, thank you!!

**Comment by mleister97** [comment]
> I added
> `...((multiple && this.isSelected(item)) && this.props.activeLabelStyle)`
> to the text-Tag on line 331 to your latest beta version. Now its working for me.
> 
> (with version 3.1.12-beta.1 alone, i wasn't able to color the text)

Seems fine for me, thank you!!

**Comment by hossein-zare** [comment]
@LWlook @mleister97 
There's another property for it called `activeLabelStyle`.
I published **3.1.12-beta.4** just now. (Updated)

```javacript
activeItemStyle={{ backgroundColor: '#dfdfdf' }}
activeLabelStyle={{ color: 'red' }}
```

**Comment by mleister97** [comment]
Thank you. I would also suggest (some improvements):

- Possibility to show tick icon on left side
- Possibility to show tick icon on single-value dropdowns
- Possibility to reset the state of the dropdown from parent (because sometime you want to reset the whole formular with a button comming from outside)

**Comment by hossein-zare** [comment]
@mleister97 
It's possible to reset the state.
Did you mean this?
```javascript
this.setState({
    country: null    [or]    countries: []
});
```

**Comment by mleister97** [comment]
Yeah but from outside the component :D
Just like calling dropDown.reset() from parent-component


Normally the state should be controlled by parent. This is not the case here, so such a function would really be helpful

**Comment by hossein-zare** [comment]
@mleister97 
Please install `react-native-dropdown-picker@3.1.12-beta.5`

**New property to control the picker**
https://github.com/hossein-zare/react-native-dropdown-picker#controller

I'm going to release it if it's working well.
